import type { Metadata } from 'next';
import { Public_Sans as FontSans, Ibarra_Real_Nova as FontSerif } from 'next/font/google';

import '@/styles/globals.css';

import Footer from '@/components/footer';
import Header from '@/components/header';

const sans = FontSans({
  preload: true,
  display: 'swap',
  variable: '--ff-sans',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});
const serif = FontSerif({
  preload: true,
  display: 'swap',
  variable: '--ff-serif',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Frontend Mentor | Minimalist Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${serif.variable} ${sans.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
